name: CI/CD pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Dependabot
      uses: dependabot/actions/dependabot-core@v2
      with:
        schedule: 'daily'
        labels: 'security'
        autoupdate: 'false'
        
    - name: Send email notification
      uses: ncipollo/send-email-action@v1
      with:
        to: 'geysonleone@gmail.com'
        subject: 'Dependabot results'
        body: 'Dependabot found and fixed security vulnerabilities in your code.'

