name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Query Dependabot Alerts 
        uses: pwned-17/check-dependabot@v1.2.9
