name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    version: 2
    updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

    - name: Generate Alerts
      uses: actions/bin/filter@v2
      with:
        args: dependabot-upgrade
        severity: warning
      id: filter

    - name: Send Alerts
      if: steps.filter.outputs.alerts
      uses: actions/email@v2
      with:
        to: geysonleone@gmail.com
        subject: Dependabot Alerts
        body: ${{ toJson(steps.filter.outputs.alerts) }}
