name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Dependabot
      uses: dependabot/github-actions/dependabot-core@v1
      with:
        args: upgrade

    - name: Send Alerts
      uses: actions/email@v2
      if: failure()
      with:
        to: geysonleone@gmail.com
        subject: Dependabot Alerts
        body: |
          The pipeline has failed. Check the logs for more information.
