name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout
    uses: actions/checkout@v3.3.0
  
 
      - name: Fetch Metadata from Dependabot PRs
     uses: dependabot/fetch-metadata@v1.3.6

      - name: Run Dependabot
    uses: dependabot/actions/dependabot-core@v1.3.6
    with:
      args: upgrade
